# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb7777e1c2194ef87a6438d74e378f531f9052ddf29bd161f0b27995644502cea0437a75424da3a64f2f1201a3666922258cb64cd9fedfb1142d1669ca916b3c

test:
  secret_key_base: 1387dcc21aca9c84e04d6bbbd4c1549e157f0cf61d85bb728315fad9988a7870f52036d610c0e7b8c1c97914d4a7f98b4599b9376c3074fc9cd01adf0bf3a23e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
